stages:
  - package

build_backend:
  stage: build
  image: node:16-alpine
  script:
    - npm install
    - npm run build
  
package_backend:
  stage: package
  image: docker:20.10.16
  tags:
    - docker
  services:
    - docker:20.10.16-dind
  before_script:
    - apk add --no-cache nodejs npm
    - echo "$CI_GITLAB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  dependencies:
    - build_backend
  




