stages:
  - test
  - package

test backend:
  stage: test
  script:
    - echo "this is test stage"

package_backend:
  stage: package
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_NAME: library
  before_script:
    - echo "$CI_GITLAB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -t $IMAGE_NAME:$COMMIT_REF_NAME-$CI_PIPELINE_ID .
    - docker push $IMAGE_NAME:$COMMIT_REF_NAME-$CI_PIPELINE_ID
  




