stages:
  - build
  - package
  - deploy
  - send-email

build backend:
  stage: build
  image: node:16-alpine
  script:
    - npm install
    - npm run build

package_backend:
  stage: package
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_NAME: library
  script:
    - npm install
    - npm run build
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin $CI_GITLAB_TOKEN
    - docker build -t $IMAGE_NAME:$COMMIT_REF_NAME-$CI_PIPELINE_ID .
    - docker push $IMAGE_NAME:$COMMIT_REF_NAME-$CI_PIPELINE_ID
  dependencies:
    - "build backend"
# deploy backend:
#   stage: deploy
#   script:
#     - docker login
#     - login to ec2 machine
#     - install docker
#     - deploy ec2

# sendEmail:
#   stage: send-email
