stages:
  - package
  - deploy
  # - container_scanning
  # - sonar scan



#code quality checking
# sonar scanning:
#   stage: 


package_backend:
  stage: package
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  before_script:
    - apk add --no-cache nodejs npm
    - echo "$CI_GITLAB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - npm install
    - npm run build
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

#container Scanning vulnerbility checking(Trivy)
# container scanning:
#   stage: scan

deploy backend:
  image: ubuntu-latest
  stage: deploy
  before_script:
    - apt-get update -y && apt-get install jq -y
  script:
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - aws ecr get-login
    - docker push $IMAGE_TAG
    - docker logout
    - apt-get install wget -y
    - pwd
    - ls
    - chmod +x deploy/ec2/*
    - deploy/ec2/deploy.sh


# sendEmail:
#   stage: send-email

# registry.gitlab.example.com/my_group/my_project CI_REGISTRY_IMAGE format
# CI_COMMIT_REF_SLUG --> CI_COMMIT_REF_NAME in lowercase, shortened to 63 bytes, and with everything except 0-9 and a-z replaced with -.
# No leading / trailing -. Use in URLs, host names and domain names.
