FROM node:16-alpine AS builder

WORKDIR /app

COPY dist /app

COPY package*.json ./

RUN npm install



FROM gcr.io/distroless/nodejs16-debian11

COPY --from=builder /app /app

WORKDIR /app

EXPOSE 5000

CMD ["node", "index.bundle.js"]
